remote_theme: "mmistakes/minimal-mistakes@4.28.1"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

minimal_mistakes_skin: "default"

title: "Lillian LeRoy"
logo: "LillianLeRoyHeadshot.JPG"
description: "Engineering Portfolio & Academic Research"
url: "https://FiredElectron.github.io"
baseurl: "/assets/images/LillianLeRoyHeadshot.JPG"

# Force all layout views to expand to the maximum full-width column size
defaults:
  - scope:
      path: "" # Applies to all files in the repository
    values:
      layout: "single"
      classes: wide
